export enum Gender {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    NON_BINARY = 'NON_BINARY',
    TRANSGENDER_MALE = 'TRANSGENDER_MALE',
    TRANSGENDER_FEMALE = 'TRANSGENDER_FEMALE',
    GENDER_FLUID = 'GENDER_FLUID',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}